//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C246SpellBook_V_2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HotKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HotKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C246SpellBook_V_2.Properties.HotKeys", typeof(HotKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+I.
        /// </summary>
        internal static string ADD_SPELL_TO_INNATE {
            get {
                return ResourceManager.GetString("ADD_SPELL_TO_INNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+P.
        /// </summary>
        internal static string ADD_SPELL_TO_PREPARED {
            get {
                return ResourceManager.GetString("ADD_SPELL_TO_PREPARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ADD_SPELL_TO_SPELLBOOK {
            get {
                return ResourceManager.GetString("ADD_SPELL_TO_SPELLBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        internal static string COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+N.
        /// </summary>
        internal static string CREATE_SPELL {
            get {
                return ResourceManager.GetString("CREATE_SPELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+B.
        /// </summary>
        internal static string CREATE_SPELLBOOK {
            get {
                return ResourceManager.GetString("CREATE_SPELLBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+N.
        /// </summary>
        internal static string DELETE_SPELL {
            get {
                return ResourceManager.GetString("DELETE_SPELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+B.
        /// </summary>
        internal static string DELETE_SPELLBOOK {
            get {
                return ResourceManager.GetString("DELETE_SPELLBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+N.
        /// </summary>
        internal static string DUPLICATE_SPELL {
            get {
                return ResourceManager.GetString("DUPLICATE_SPELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+B.
        /// </summary>
        internal static string DUPLICATE_SPELLBOOK {
            get {
                return ResourceManager.GetString("DUPLICATE_SPELLBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+E.
        /// </summary>
        internal static string EDIT_SPELL {
            get {
                return ResourceManager.GetString("EDIT_SPELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EXPORT_RAW_TO_XML {
            get {
                return ResourceManager.GetString("EXPORT_RAW_TO_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+S.
        /// </summary>
        internal static string EXPORT_SPELLBOOK_TO_TEXT {
            get {
                return ResourceManager.GetString("EXPORT_SPELLBOOK_TO_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+S.
        /// </summary>
        internal static string EXPORT_SPELLBOOK_TO_XML {
            get {
                return ResourceManager.GetString("EXPORT_SPELLBOOK_TO_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IGNORE_UNCHECKED_COMPONENTS {
            get {
                return ResourceManager.GetString("IGNORE_UNCHECKED_COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IMPORT_RAW_FROM_XML {
            get {
                return ResourceManager.GetString("IMPORT_RAW_FROM_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+O.
        /// </summary>
        internal static string IMPORT_SPELLBOOK_FROM_XML {
            get {
                return ResourceManager.GetString("IMPORT_SPELLBOOK_FROM_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+R.
        /// </summary>
        internal static string OPEN_DATA_EDITOR {
            get {
                return ResourceManager.GetString("OPEN_DATA_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+I.
        /// </summary>
        internal static string REMOVE_SPELL_FROM_INNATE {
            get {
                return ResourceManager.GetString("REMOVE_SPELL_FROM_INNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+P.
        /// </summary>
        internal static string REMOVE_SPELL_FROM_PREPARED {
            get {
                return ResourceManager.GetString("REMOVE_SPELL_FROM_PREPARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Del.
        /// </summary>
        internal static string REMOVE_SPELL_FROM_SPELLBOOK {
            get {
                return ResourceManager.GetString("REMOVE_SPELL_FROM_SPELLBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RESETS_TO_DEFAULT {
            get {
                return ResourceManager.GetString("RESETS_TO_DEFAULT", resourceCulture);
            }
        }
    }
}
